cfgen: cfgen execution fails outside of hctl
cfgen script imports some of the hax modules and thus require to have
hax modules path accessible if executed explicitly post installation.
e.g.
```
[root@ssc-vm-g4-rhev4-0554 ~]# /opt/seagate/cortx/hare/bin/cfgen
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/cfgen", line 17, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

Solution:
Add hax module paths for imports to be available to cfgen script as
part of installation.

Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>