hax/Makefile: Use `python3-config`
This fixes the following error:

    + make -C hax
    /bin/bash: python-config: command not found
    make: Entering directory `/data/hare/hax'
    cpp -MM -MG -I../../mero  -DM0_INTERNAL= -DM0_EXTERN=extern hax/hax.c |\
     sed -r 's%^(.+)\.o:%hax/\1.d hax/\1.o:%' >hax/hax.d
    make: Leaving directory `/data/hare/hax'
    /bin/bash: python-config: command not found
    make: Entering directory `/data/hare/hax'
    cc -g -Werror -Wall -Wextra -Wno-attributes -Wno-unused-parameter -fPIC -I../../mero  -DM0_INTERNAL= -DM0_EXTERN=extern  -c -o hax/hax.o hax/hax.c
    hax/hax.c:22:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    make: *** [hax/hax.o] Error 1
    make: Leaving directory `/data/hare/hax'