Problem: build-ees-ha fails with cryptic error
`build-ees-ha`, which is not idempotent, fails with cryptic error message
if it's started the second time, when floating IPs are already assigned:
```
[root@smc7-m11 520422]# /opt/seagate/eos/hare/libexec/build-ees-ha /var/lib/hare/cluster.yaml /var/lib/hare/build-ees-ha-args.yaml
Adding the roaming IP addresses into Pacemaker...
Error: missing value of '24' option
```

The `ip` command, used in calculating netmask value, outputs two lines
in this case -- one for actual, another for virtual interface.

Solution: take the first netmask value.

Closes #370.