EOS-27016: device info accessed before saving
1. Hare mini provisioner saves local storage devices facts and information
during mini-provisioner prepare stage. This information is read during the
config stage to generate motr configuration. hare requires devices
information form all the nodes to be available in Consul to generate the
motr configuration on every node. All the nodes in a cluster are provisioned
in-parallel, thus, it is possible that a node might be executing prepare
stage while the othe might already have started with config. This can be
illustrated as follows,
Node 0
```
2022-01-25 22:05:24 cortx_setup [62]: INFO [_provision_components] /opt/seagate/cortx/hare/bin/hare_setup config --config yaml:///etc/cortx/cluster.conf --services all
2022-01-25 22:05:32 cortx_setup [62]: ERROR [main] error(1): config phase of hare, failed. b''
2022-01-25 22:05:32 cortx_setup [62]: ERROR [main] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cortx/setup/cortx_setup.py", line 132, in main
    rc = command.process()
  File "/usr/lib/python3.6/site-packages/cortx/setup/cortx_setup.py", line 120, in process
    CortxProvisioner.cluster_bootstrap(self._args.cortx_conf, force_override)
  File "/usr/lib/python3.6/site-packages/cortx/provisioner/provisioner.py", line 263, in cluster_bootstrap
    CortxProvisioner._provision_components(cortx_conf, mini_prov_interfaces, apply_phase)
  File "/usr/lib/python3.6/site-packages/cortx/provisioner/provisioner.py", line 230, in _provision_components
    component_name, err)
cortx.provisioner.error.CortxProvisionerError: error(1): config phase of hare, failed. b''
```
Node 1
```
2022-01-25 22:05:23 cortx_setup [63]: INFO [_provision_components] /opt/seagate/cortx/hare/bin/hare_setup prepare --config yaml:///etc/cortx/cluster.conf --services all
```
As above, node1 is already executing config stage while node1 is still preparing
and thus, node1 config stage fails.

2. `confd_p` variable accessed without being set in cfgen
3. RuntimeError exception hit with latest KV structure,
```
  File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/util.py", line 1656, in get_process_node
    raise RuntimeError(f'XXX proc_fid:{proc_fid} fidk:{fidk}'
RuntimeError: XXX proc_fid:0x7200000000000001:0x17e fidk:382len:2

[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2279 /]# consul kv get -recurse | grep "processes/0x7200000000000001:0x17e:"
cortx-data-headless-svc-ssc-vm-g3-rhev4-2107/processes/0x7200000000000001:0x17e:{"state": "M0_CONF_HA_PROCESS_STARTING", "type": "M0_CONF_HA_PROCESS_M0D"}
m0conf/nodes/0x6e00000000000001:0x168/processes/0x7200000000000001:0x17e:{"name": "m0_server", "state": "online"}
m0conf/nodes/0x6e00000000000001:0x17a/processes/0x7200000000000001:0x17e:{"name": "hax", "state": "online"}
```
Apprently, there can be multiple keys for the given query.
4. update-consul-conf only considers server nodes,
```
2022-01-26 04:13:31,080 [ERROR] Error performing configuration : 2022-01-26 04:13:31,061 [ERROR] Exiting due to a failure: Logic error: node_name=cortx-server-headless-svc-ssc-vm-g3-rhev4-2107 not found in /etc/cortx/hare/config//e6cb8b3ffce845539299dd08a42ec3a3/consul-agents.json
```

Solution:
1. Repeat Consul fetch operation until the corresponding device information is
available.
2. Declare and initialize `confd_p` unconditionally.
3. Allow length of the query result to be > 1.
4. Consider both, server and client nodes in update-consul-conf.

Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>