fixup! hax: fix rpm build for ARM64 Motr port
Fix the change at commit c8363d2: the `-include config.h`
compiler option was specified wrongly in the python list
of parameters, which resulted in compilation error:

    'config.h': No such file or directory

Solution: make `-include` and `config.h` a separate list
elements.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>